In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
# 설치할 때 다른 파이썬 코드랑 섞어서 쓰면 안되고 주석도 처리하면 안됨

In [33]:
import numpy as np

In [9]:
#Creating a Nymoy Array
my_list = [1, 2, 3, 4, 5, 6]

my_array = np.array(my_list)
print(my_array)

[1 2 3 4 5 6]


In [14]:
#.dtype attribute

a = np.array([1, "A", True])
print(a.dtype)

b = np.array([1, 2, 3,])
print(b.dtype)

c = np.array([1.1, 2.3])
print(c.dtype)

<U11
int32
float64


In [24]:
#Size COmparison of ndarray and list objects

from sys import getsizeof

lst = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(getsizeof(lst)) 

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(getsizeof(arr)) 

"""정수값 자체는 4바이트지만 각 객체이기 때문에 객체 저장을 리스트가 저장해주어 메모리정보, 헤드정보도 다 저장되어 
리스트 크기가 일정 수준 이상이면 어레이가 차지하는 것보다 리스트가 더 큼 그러므로 데이터 크기가 크면 어레이가 더 우수
"""


136
144


In [26]:
#operation and np.sqrt
lst = [1, 2, 3]
arr = np.array(lst)

lst += 1 #리스트는 '리스트 컴프리헨션'을 이용해야 함

TypeError: 'int' object is not iterable

In [32]:
lst = [1, 2, 3]
arr = np.array(lst)

arr +=3
print(arr)

arr2 = np.sqrt(arr)
print(arr2) #리스트 컴프리헨션 보다 훨씬 편리


[4 5 6]
[2.         2.23606798 2.44948974]


In [62]:
"""
Exercise
"""

# 세 번의 시험에 대한 각 학생 별 점수를 Numpy 배열로 선언하라.

test_1 = np.array([92, 94, 88, 91, 87])
test_2 = np.array([79, 100, 86, 93, 91])
test_3 = np.array([87, 85, 72, 90, 92])

# 세 번째 시험 채점에 문제가 발견됨. 시험에 2점을 더해 새로운 배열 test_3_fixed에 저장하라.
test_3_fixed = test_3 + 2 #원소단위의 연산 so easy


# 학생 별 평균 시험 점수 계산 위해 학생 별 전체 시험 점수 총합을 total_grade에 저장

total_grade = test_1 + test_2 + test_3_fixed

# 학생 별 평균 시험 점수를 final_grade에 저장하라.
final_grade = total_grade / 3

print(final_grade)


# Jeremy의 두 번째 시험점수를 jeremy_test_2에 저장하라
# Manual 과 Adwoa의 첫 번째 시험점수를 manual_adwoa_test_1에 저장하라.

jeremy_test_2 = test_2[3]
print(jeremy_test_2)

manual_adwoa_test_1 = [test_1[1], test_1[2]]
print(manual_adwoa_test_1)


# 전체 학생들의 점수를 2차원 배열 student_scores에 저장하세요
student_scores = np.array([test_1, test_2, test_3_fixed])
print(student_scores)

# 2차원 배열로부터 Tanya의 세 번째 시험 점수를 가져와.
print(student_scores[2][0]) # student_scores로 2차원 배열로 저장한 상태에서 세번째 시험은 두번째꺼고 타냐는 첫번째 학생이니가

# studnt_scores로 부터 Cody의 전체 시험 점수를 구하시오
print(student_scores[:, 3]) #콜론은 다 가져와!

[86.66666667 93.66666667 82.66666667 92.         90.66666667]
93
[94, 88]
[[ 92  94  88  91  87]
 [ 79 100  86  93  91]
 [ 89  87  74  92  94]]
89
[91 93 92]


In [76]:
"""
Logical Opreration with Arrays
"""

#masking
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
lst > 5
print(arr)

# select using logical operations
selected = arr[arr > 5]
print(selected)

selected_2 = arr[(arr > 7) | (arr < 2)] # '|'는 놀리합이므로 해당하는 거 다 출력
print(selected_2)

sel_3 = arr[(arr > 5) & (arr < 8)] # '&'는 논리곱으로 겹치는 부분만 출력

print(sel_3)

# combined logical operations

[ 1  2  3  4  5  6  7  8  9 10]
[ 6  7  8  9 10]
[ 1  8  9 10]
[6 7]
