In [7]:
pip install numpy # 얘네 쓸 때마다 

In [16]:
import numpy as np #불러와야 함.. 귀찮다..

In [17]:
"""
Numpy Array Attributes
넘파이의 배열 또한 객체로 존재함
"""

#Creating an array
print(np.arange(3)) # stop
print(np.arange(2, 5)) # strt, stop
print(np.arange(1, 9, 2)) # start, stop, step

[0 1 2]
[2 3 4]
[1 3 5 7]


In [30]:
# Random number generator

arr1 = np.random.randint(10, size = (5)) # 0 ~ 9 중에 다섯개 랜덤!
print(arr1)

arr2 = np.random.randint(100, size = (3, 5)) #size = (행, 열)
print(arr2)

arr3 = np.random.randint(10, size = (3, 2, 2)) # 행 두 개와 열 두 개짜리가 있는 것들이 세 개 생김
print(arr3)

[7 3 9 9 1]
[[38 69 41 19 68]
 [ 2 83 26 35 63]
 [99 76 74 55 12]]
[[[2 6]
  [7 9]]

 [[6 9]
  [1 7]]

 [[0 2]
  [3 4]]]


In [42]:
# Attributes

print("arr1.ndim", arr1.ndim) #1차원 배열이므로 1이라 나오
print("arr2.ndim", arr2.ndim) #2차원 배열이므로 2라고 나옴

print("arr2.shape", arr2.shape) #배열 차원 크기 = 형상
print("arr2.size", arr2.size) #배열의 원소 개수
print("arr2.dtype", arr2.dtype) #데이터타입
print("arr2.itemsize", arr2.itemsize) #사이즈인데 정수는 4바이트니까 4


arr4 = np.array([1.5, 2.3, 3.4])
print("arr4.itemsize", arr4.itemsize) #실수는 아이템 하나당 8바이트

print("arr2.nbytes", arr2.nbytes) #배열이 차지하는 전체 메모리 공간 60 왜냐 총15개고 하나당 4바이트니까!

arr1.ndim 1
arr2.ndim 2
arr2.shape (3, 5)
arr2.size 15
arr2.dtype int32
arr2.itemsize 4
arr4.itemsize 8
arr2.nbytes 60


In [50]:
"""
Array Slicing : 배열의 부분집합을 선택
이거 중요하다고 하심
"""

arr = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(arr[::3]) #첨부터 끝까지 선택하는데, 3스텝이니까 두칸씩 건너뛰어
print(arr[1:5]) #1부터 4까지
print(arr[:7]) # 첨부터 6까지
print(arr[1:5:2]) #0부터 4까지인데 1칸씩 건너뛰어!


[0, 3, 6, 9]
[1, 2, 3, 4]
[0, 1, 2, 3, 4, 5, 6]
[1, 3]


In [79]:
"""
Subarrays as Views
배열 슬라이스는 복사본이 아닌 뷰
- 배열 슬라이스 값을 변경 ==> 원본 배열 값도 변경됨 (리스트는 원본은 그대로이니 서로 다름)
"""

np.random.seed(1) #계속 동일한 값 나오게 함
arr = np.random.randint(10, size = (3, 4))
print(arr, '\n')

arr_sub = arr[:2, :2]
print(arr_sub, '\n')


arr_sub[0, 0] = -1 #원래 5인 부분을 -1로 바꿈
print(arr_sub, '\n') #-1로 바뀜

print(arr) #원본 배열 값도 -1로 바뀜!



[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]] 

[[5 8]
 [0 0]] 

[[-1  8]
 [ 0  0]] 

[[-1  8  9  5]
 [ 0  0  1  7]
 [ 6  9  2  4]]


In [82]:
#.copy()

np.random.seed(1) #계속 동일한 값 나오게 함
arr = np.random.randint(10, size = (3, 4))
print(arr, '\n')

arr_sub = arr[:2, :2].copy() #복사본은 원본 배열을 유지 시켜줌
print(arr_sub, '\n')

arr_sub[0, 0] = -1
print(arr_sub, '\n')

print(arr) #복사본만 -1로 바뀌고 원본은 그대애앵로

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]] 

[[5 8]
 [0 0]] 

[[-1  8]
 [ 0  0]] 

[[5 8 9 5]
 [0 0 1 7]
 [6 9 2 4]]


In [85]:
"""
Reshaping of Arrays
"""

arr = np.arange(1, 10)
print(arr)

grid = arr.reshape(3, 3) #배열 형상을 변경함 원래 일자로 주우욱 있던 걸 바꿀 수 있는거
print(grid)



[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [90]:
#np.newaxis ==> 배열의 추가 차원

arr = np.array([1, 2, 3])
print(arr)
print("arr.ndim = ", arr.ndim)
print("arr.shape = ", arr.shape)

arr_new = arr[np.newaxis, :] #newaxis를 어디에 넣느냐에 따라 쉐입이 달라짐 이건 1X3
print(arr_new)
print("arr.new.ndim = ", arr_new.ndim)
print("arr.new.shape = ", arr_new.shape)


arr_new2 = arr[:, np.newaxis] #newaxis를 어디에 넣느냐에 따라 쉐입이 달라짐 이건 3X1
print(arr_new2)
print("arr.new2.ndim = ", arr_new2.ndim)
print("arr.new2.shape = ", arr_new2.shape)

[1 2 3]
arr.ndim =  1
arr.shape =  (3,)
[[1 2 3]]
arr.new.ndim =  2
arr.new.shape =  (1, 3)
[[1]
 [2]
 [3]]
arr.new2.ndim =  2
arr.new2.shape =  (3, 1)


In [96]:
#np.concatanate() ==> 배열 연결 메소드

arr_1 = np.array([1, 2, 3,])
arr_2 = np.array([4, 5, 6])
arr_3 = np.array([7, 8, 9])

arr_total = np.concatenate([arr_1, arr_2, arr_3]) #배열을 차례로 붙여주
print(arr_total)


#np.vstack() : 종 방향으로 배열 연결

arr_total = np.vstack([arr_1, arr_2, arr_3])
print(arr_total)

#np.hastack() : 횡 방향으로 배열 연결

arr_total = np.hstack([arr_1, arr_2, arr_3])
print(arr_total)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [99]:
"""
Array Splitting
배열 분할
"""

arr = [1, 2, 3, 99, 99, 3, 2, 1]
print(arr)

arr_1, arr_2, arr_3 = np.split(arr, [3, 5]) #np.split(자르고자 하는 변수, [어디서 몇 개 자를지] )
#0번째~2번째 자르고 3번째~4번째 자르고, 5번째~마지막 자르고

print(arr_1)
print(arr_2)
print(arr_3)



arr_4, arr_5 = np.split(arr, [4]) #0번째부터 3번째까지 자르고 4번째부터 마지막까지
print(arr_4)
print(arr_5)

[1, 2, 3, 99, 99, 3, 2, 1]
[1 2 3]
[99 99]
[3 2 1]
[ 1  2  3 99]
[99  3  2  1]
