In [19]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [16]:
import numpy as np

In [32]:
"""
Computing reciprocals in loops
역수를 계산하는 함수
"""

#Function for computing reciprocals using looping
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 /values[i]
        return output #리스트를 가져와서 그것의 역수를 구하는 것


values= np.random.randint(1, 10, size = 5) #1부터 10까지의 랜덤 값 5개를 가져오게 됨
print(values) #계속 랜덤 값이 계속 바뀌는 게 싫으면 values 위에 np.random.seed(0) 해놓으면 됨

output = compute_reciprocals(values) #역수를 만들어주는 함수를 호출해서 거기에 우리가 만든 인자를 넣어줌
print(output)


[6 6 7 1 7]
[ 1.66666667e-001 -1.52907204e+028  1.67982320e-321  2.20687563e-312
  0.00000000e+000]


In [37]:
"""
Comparison : Loops vs ufuncs(vectorized)
"""

# looping on a big array
big_array = np.random.randint(1, 100, size = 1000000) # 겁나 큰 난수 배열
print(big_array)



#magic function (e,g,m %timeit)
%timeit compute_reciprocals(big_array) #특정 코드의 실행시간이 얼마나 걸리는지 체크하기 위하 기능이 %timeit => 주피터에서만 돌아감

[64 32 84 ... 24 18 50]
64 µs ± 4.47 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [41]:
#vectorized operations 벡터화 연산으로 해보기

%timeit 1 / big_array #넘파이에서는 심플하게 하나의 연산식으로 표현 가능. 컴파일 계층에서 하기 때문에 훨씬 빠름.


7.6 ms ± 312 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [51]:
"""
numpy.ufunc
넘파이 유니버셜 함수
"""

np.random.seed(1)
arr1 = np.random.randint(10, size = 5)
arr2 = np.random.randint(10, size = 5)
print(arr1, arr2)

arr1 = arr1 - 2 #첫번째 arr1에 대한 모든 원소에 2씩 빼줄 수 있는 so 간단
print(arr1)

arr3 = arr1 + arr2
print(arr3)

arr4 = np.random.randint(10, size=(3, 5)) #10안으로 3개행 5개열
print(arr4)

print(arr4**2) #arr4의 모든 원소에 제곱을 해주는 so easy

for value in arr4: #value 안에 있는 4차원 배열 하나씩 꺼내와서
    print(value**2) #코드 자체도 긴 건 아니지만 '벡터화 연산이 아니어서 느림!' 무조건 연산 커다란 거 하면 넘파이가 짱


[5 8 9 5 0] [0 1 7 6 9]
[ 3  6  7  3 -2]
[ 3  7 14  9  7]
[[2 4 5 2 4]
 [2 4 7 7 9]
 [1 7 0 6 9]]
[[ 4 16 25  4 16]
 [ 4 16 49 49 81]
 [ 1 49  0 36 81]]
[ 4 16 25  4 16]
[ 4 16 49 49 81]
[ 1 49  0 36 81]


In [56]:
"""
UFuncs : Array Arithmetic
"""

# Basic arithmetic operations on an array

x = np.arange(4) 
print(x) #0 부터 3까지 네 개 나옴
print("x + 5 =", x + 5) # 다 계산 됨
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x ** 2 =", x ** 2)

# 내가 정확한 유니버설 function명을 통해 구현하고 싶으면 넘파이에서 제공해주는 함수명으로 호출해도 됨
print("x - 5 =", np.add(x, 5))
print("x * 2 =", np.subtract(x , 2))
print("x / 2 =", np.multiply(x , 2))
print("x ** 2 =", np.power(x, 2)) #넘파이 function으로 해도 똑같이 나옴


[0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x ** 2 = [0 1 4 9]
x - 5 = [5 6 7 8]
x * 2 = [-2 -1  0  1]
x / 2 = [0 2 4 6]
x ** 2 = [0 1 4 9]


In [65]:
"""
UFuncs : Absolute Value

프로그램 랭귀지에서 기본으로 제공하는 함수 : built-in function
"""

# np.abs() : 절대값 함수 (파이썬에서 기본으로 제공하긴 하지만, 이건 벡터화 연산이라 빠름)
x = np.array([-2, -1, 0, 1, 2])
print(np.abs(x)) #절대값 구해줌


y = np.array([3-4j, 4-3j, 2+0j, 0+1j]) #복소수
print(np.abs(y)) #복소수의 절대값도 구해줌

[2 1 0 1 2]
[5. 5. 2. 1.]


In [73]:
 """
 UFuncs : linspace()
 np.linspace(start, stop, num) : 선형 간격의 벡터를 생성해주는 유용한 메서드
 - 다양한 벡터/행렬 생성에 자주 사용
 """

x = np.linspace(0, 100, 5) #0부터 100 사이를 5구간으로 쪼개서, 쪼갠 구간의 기준점을 해당 배열의 원소로 할당
print(x)


[  0.  25.  50.  75. 100.]


In [78]:
"""
UFuncs : Trigonometric Functions 
삼각함수 : 데이터 과학에서 자주 사용되는 함수
- np.sin() : 사인 함수
- np.cos() : 코사인 함수
- np.tan() : 타젠트 함수
역삼각 함수 : np.arcsin(), np.arccos(), np.arctan()
"""

#각도를 원주율 파이를 기준으로 세구간으로 나누고 각도의 배열을 theta라고 해보자 
theta = np.linspace(0, (np.pi), 3) #0부터 3.14까지 3구간으로 나누면 구간은?
print(theta)

print(np.sin(theta)) #각각의 쎼타 값에 대하여 사인 연산을 수행
print(np.cos(theta))
print(np.tan(theta))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [80]:
"""
UFuncs : etc.
지수와 로그 : np.exp(), np.power(), np.log(), np.log10()
그 외 : 쌍곡선 삼각함수, 비트연산, 비교 연산자, 라디안 등
scipy.special : 고급 수치연산을 유니버설 함수 형태로 제공하는 패키지
- 감마함수, 가우스 적분, 보수/역수 등을 계산할 때... 쓰려면 설치해야 함
"""


'\nUFuncs : etc.\n지수와 로그 : np.exp(), np.power(), np.log(), np.log10()\n그 외 : 쌍곡선 삼각함수, 비트연산, 비교 연산자, 라디안 등\nscipy.special : 고급 수치연산을 유니버설 함수 형태로 제공하는 패키지\n- 감마함수, 가우스 적분, 보수/역수 등을 계산할 때... 쓰려면 설치해야 함\n'

In [86]:
"""
UFuncs : Aggregation
데이터의 기술 통계를 위한 집계 함수 제공
reduce() : 배열을 특정 연산으로 축소
accumlate() : 계산의 '중간 결과'들을 배열로 저장
"""

# 각각의 원소에 대해 연산을 수행한 결과들을 집계를 해서 정보를 제공해줘야 하는 경우

x = np.arange(1, 5)
aggr = np.add.reduce(x)
print(aggr) #1부터 4까지로 나온 값을 다 더해줌

aggr2 = np.multiply.reduce(x)
print(aggr2) #1부터 4까지로 나온 값을 다 곱해줌


# 결과가 누적되는 과정을 배열로 저장해서 리턴해줌
accum = np.add.accumulate(x) #위에서 x에 넣어준 1부터 4까지의 값을 각각 더함. 1에 2 더하고 그럼 3 나오니까 거기에 3더하고 그럼 6나오는데 6에 4더하면 10 
print(accum) 

accum = np.multiply.accumulate(x) #각 중간 결과들의 곱셈
print(accum)

10
24
[ 1  3  6 10]
[ 1  2  6 24]


In [106]:
"""
Summing the Values in an Array
"""

np.random.seed(3)
arr = np.random.rand(1000000) #rand : 0~1 사이의 실수형태의 난수배열을 100만 가지 만듦
print(arr)

print("sum = ", np.sum(arr)) #100만 개의 총합을 빠르게 구해줌

%timeit sum(arr) #기본 파이썬 속도
%timeit np.sum(arr) #넘파이 속도 100배 빠름

[0.5507979  0.70814782 0.29090474 ... 0.93033748 0.80429816 0.47400579]
sum =  500422.19897015305
246 ms ± 82.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
2.24 ms ± 206 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [122]:
#Other aggr. functions

print(arr)
print('max = ', np.max(arr)) #배열의 최댓값
print('min = ', np.min(arr)) #최솟값
print('mean = ', np.mean(arr)) #평균값
print('median = ', np.median(arr)) #중앙값
#print('percentile = ', np.percentile(arr), 10) #하위 10프로의 원소

print(np.any(arr>1)) #참을 만족하는 원소가 있는지
print(np.all(arr>0)) #모든 원소들이 참을 만족하는지

[0.5507979  0.70814782 0.29090474 ... 0.93033748 0.80429816 0.47400579]
max =  0.9999996367889004
min =  1.5496004267534502e-06
mean =  0.500422198970153
median =  0.5005659265960778
False
True


In [126]:
"""
Multi Dimensional Aggregates
다차원 집계 : 특정 차원을 기준으로 집계
- axis 속성 : 0이면 row(행) 값 아래로 쫙 더해주고, 1이면 colum(열) 값 쫙 더해주고
"""

np.random.seed(5)
mult = np.random.randint(10, size=(3, 4))
print(mult)
print(np.sum(mult, axis = 0)) # 세로로 더한 값

print(np.sum(mult, axis = 1)) #가로로 더한 값


[[3 6 6 0]
 [9 8 4 7]
 [0 0 7 1]]
[12 14 17  8]
[15 28  8]
